friction2d/friction

src/app/GUI/ColorWidgets/colorlabel.cpp, src/app/GUI/ColorWidgets/colorvaluerect.cpp, src/app/GUI/RenderWidgets/outputsettingsdialog.cpp, src/app/GUI/canvaswindow.cpp, src/app/GUI/canvaswindowevents.cpp, src/app/GUI/glwindow.cpp, src/app/main.cpp
All the widgets which derives from QOpenGLWidget should take into account the devicePixelRatio.
=> Fixed issues with hidpi display (Canvas Area and color widgets)

src/app/GUI/RenderWidgets/outputsettingsdialog.cpp, src/app/GUI/RenderWidgets/outputsettingsdialog.h, src/app/GUI/RenderWidgets/outputsettingsdisplaywidget.cpp, src/app/GUI/RenderWidgets/outputsettingsdisplaywidget.h, src/core/ReadWrite/evformat.h, src/core/outputsettings.cpp, src/core/outputsettings.h, src/core/videoencoder.cpp, src/core/videoencoder.h
This PR adds support for video codec profiles (encode).
The following codecs now support profiles:
- H264 _(baseline/main/high)_
- ProRes _(proxy/lt/standard/hq/4444/xq)_
- AV1 _(main/high/professional)_
- VP9 _(0/1/2/3)_
- MPEG4 _(simple/core/main)_
- VC1 _(simple/main/complex/advanced)_
Support for more codecs can be added later.
**WARNING!** This commit bumps the evformat (26). Project files saved with this version or later will not be compatible with earlier versions of Friction (or enve).
Fix #129
=> Support video codec profiles

src/app/GUI/mainwindow.cpp, src/app/GUI/mainwindow.h, src/core/Boxes/boundingbox.cpp, src/core/Boxes/boundingbox.h, src/core/Boxes/textbox.h, src/core/canvas.h, src/core/canvasselectedboxesactions.cpp, src/ui/dialogs/exportsvgdialog.cpp, src/ui/dialogs/exportsvgdialog.h
The export SVG dialog will now show warnings/notes etc if some part of the project is not compatible with SVG+SMIL.
*If no warning the dialog will of course not include the warning field ;)*
Fix #174
=> Export SVG: add compatibility checks

src/app/GUI/mainwindow.cpp, src/app/GUI/mainwindow.h, src/ui/dialogs/exportsvgdialog.cpp, src/ui/dialogs/exportsvgdialog.h
Added 'Preview SVG' action to toolbar (and file menu) with shortcut 'Ctrl+F12'.
Also (re)store export dialog check boxes state (background/fixed/loop).
*I know we are in a feature freeze, but ... I was doing a lot of previews on a project yesterday and the UX is bad! Too many clicks.*
=> SVG: support quick preview

src/core/CMakeLists.txt, src/core/ShaderEffects/shadereffect.cpp, src/core/ShaderEffects/shadereffectcaller.cpp, src/core/ShaderEffects/shadereffectcaller.h, src/core/ShaderEffects/shadereffectjs.cpp, src/core/ShaderEffects/shadereffectjs.h, src/core/ShaderEffects/shadervaluehandler.cpp, src/core/ShaderEffects/shadervaluehandler.h, src/core/ShaderEffects/uniformspecifiercreator.cpp, src/core/ShaderEffects/uniformspecifiercreator.h, src/core/threadsafeqjsengine.h
This is the first refactor of the shader effects code. The goal is to keep all `QJSEngine` / `QJSValue` calculations and calls inside the `ShaderEffectJS` class.
This should improve stability when many shader effects are used in a project. See #64 for more information.
Everything should "just work" as usual, I have been careful to not modify the actual calculations or order. Tested on various projects with misc shader effects and I have not noticed any regressions.
Will provide binaries when I get the time.
***Note** that this is not a perfect fix. Qt might still crash if you have enough effects (mostly on Linux), but this PR bumps the stability to usable. The main goal is to remove usage of `QJSEngine` in shader effects with something better, this will be done in a v2 refactor sometime …
=> ShaderEffects refactor v1

src/core/svgimporter.cpp
Fixes linecap and linejoin in SVG importer (issue #197).
Further more, changed default values (no value is specified directly) of fill paint, stroke paint and stroke width according to svg specification. Fill paint = FLATPAINT, Stroke Paint = NOPAINT, StrokeWidth = 1.
Friction 0.96
SVG File
=> Fix linejoin and linecap support in SVG importer

src/app/GUI/RenderWidgets/outputsettingsdialog.cpp, src/app/GUI/RenderWidgets/outputsettingsdialog.h, src/core/CMakeLists.txt, src/core/ReadWrite/ereadstream.cpp, src/core/ReadWrite/ereadstream.h, src/core/ReadWrite/evformat.h, src/core/ReadWrite/ewritestream.cpp, src/core/ReadWrite/ewritestream.h, src/core/formatoptions.h, src/core/outputsettings.cpp, src/core/outputsettings.h, src/core/themesupport.cpp, src/core/themesupport.h, src/core/videoencoder.cpp
This PR adds support for FFmpeg options to the renderer.
You can now add key/value for meta, codec and format.
What is supported and works depends on various variables, check the FFmpeg documentation:
* https://www.ffmpeg.org/doxygen/3.2/group__metadata__api.html
* https://trac.ffmpeg.org/wiki/Encode/H.264
* https://trac.ffmpeg.org/wiki/Encode/H.265
* https://trac.ffmpeg.org/wiki/Encode/VFX
Fixes #241
=> Renderer: add FFmpeg options

src/core/svgimporter.cpp
These changes needs testing to confirm that I didn't break anything. Everything looks good on my end, but I can't test everything.
So, what does these changes do?
I was browsing Inkscape issues yesterday and came across this issue: https://gitlab.com/inkscape/inbox/-/issues/11086
Just out of curiosity I tested this in Friction, and we have the same issues.
So I fixed it.
We now handle RGB/RGBA INT/DOUBLE/PERCENT color values properly and read the `stroke-width` attribute (percent not supported yet).
=> SVG Import Changes/Fixes

src/app/GUI/graphboxeslist.cpp
Ctrl+wheel will now zoom the timeline.
* Fixes #160
* Fixes #313
=> Graph: fix inconsistent zoom behavior

src/core/PathEffects/subpatheffect.cpp, src/core/PathEffects/subpatheffect.h
When working with sub-path effect, it's very handy to have an offset parameter to easily animate the trimmed path.
Other software usually have this feature:
After Effects: https://www.youtube.com/watch?v=FovNvDpVCR4
Lottie: https://www.youtube.com/watch?v=968xhinfrYU
And here a working example of the feature in Friction:
https://github.com/user-attachments/assets/e9458d68-2ad8-4f41-8f62-3f3b5a8cd206
The only odd behavior I found is that opening old projects where "sub-path" effect is used, make Friction to crash... any idea how to solve it?
Do you know if this feature has connections with other ones that I didn't think of and could make Friction to crash or not to work properly.
Cheers
=> Adding offset parameter to sub-path effect

src/core/canvas.cpp, src/core/canvas.h, src/ui/dialogs/markereditordialog.cpp, src/ui/widgets/markereditor.cpp, src/ui/widgets/markereditor.h
Following the work on https://github.com/friction2d/friction/pull/336 here is what I think a better way to interact with the Markers editor window:
- Changed the buttons to the same row of the "close" button
- added a "clear all" option
- added tooltips for "+", "-", and "clear" buttons
=> Markers editor buttons

src/core/Boxes/animationbox.cpp, src/core/Boxes/animationbox.h, src/core/Boxes/videobox.cpp, src/core/ReadWrite/evformat.h, src/core/Sound/eindependentsound.cpp, src/core/Sound/esoundobjectbase.cpp
1. Restore proper audio mute state
2. Fix broken audio stretch
3. Read/Write audio/video stretch state
4. Undo/Redo audio/video stretch
=> Audio/Video Fixes

src/core/svgimporter.cpp
The SVG import color refactor in beta 1 introduced an issue. It took the int colors (0-255) and applied it as float (0-1) this resulted in wrong colors in some cases. We now apply the colors as int, unless % then float. Alpha is always float.
=> Svg import: fix colors

src/core/Animators/graphanimator.cpp
I've been working this weekend in the "SVG follow path" feature as [I find it pretty important](https://github.com/orgs/friction2d/discussions/326), I'm posting there all my findings but here I'm adding the final results.
Summing it all up:
- your `rotate="auto"` implementation works, but only in a specific scenario that makes sense to me. Maybe it is that Friction let's you do things so flexible that, as in this case, could look like it's not working. So, if the path or group you want to make follow a path has 'translation', 'rotation', 'scale' and 'pivot set to 0 while connected to a path to follow, the animation works fine. Fixing this could be easier for you... for me go further into the code to "fix" or to make it easier for users is almost impossible.
- I added `keyPoints` attribute …
=> SVG follow path with auto rotation and keypoints

src/core/Boxes/nullobject.cpp
Playing with null objects felt like adding a new one "crosshair":
I hope you like it.
I tried opening a file with the new target on an "old Friction build" and it opened it. It didn't show up any icon as its index didn't exist on that version but it just left it as a "blank type". Manually you can then change it to any existing type and "problem solved"... I mean, it's compatible.
Cheers
=> New null object type

src/app/GUI/RenderWidgets/outputsettingsdialog.cpp, src/app/GUI/RenderWidgets/outputsettingsdialog.h, src/app/GUI/canvaswindowevents.cpp, src/core/Animators/outlinesettingsanimator.cpp, src/core/Animators/outlinesettingsanimator.h, src/core/Animators/paintsettingsanimator.cpp, src/core/Animators/paintsettingsanimator.h, src/core/Animators/qrealanimator.cpp, src/core/FileCacheHandlers/filehandlerobjref.cpp, src/core/FileCacheHandlers/filehandlerobjref.h, src/core/Paint/simplebrushwrapper.h
Found via `codespell -q 3 -L indexin,kno,rightt,thist,uptodate`  
Closes #360
This PR is untested. Also there was hesitance for me around fixing the following typos (so I didn't).
https://github.com/search?q=repo%3Afriction2d%2Ffriction%20chaning&type=code
Is the word here, 'changing' ?
https://github.com/search?q=repo%3Afriction2d%2Ffriction%20preffered&type=code  
This should probably be 'preferred' but there are many instances of it and probably should be left alone.
=> Fix source typos

src/core/Boxes/boundingbox.cpp
It took me some time figuring the problem out: the available functions we were using were dependent of the **object scale** and were kind of scaling the transform when trying to align the pivot to the scene...
Well, it's fixed now. 
With this fix I think there is no other open issue about the new Pivot alignment, right?
=> Fix "Align pivot relative to scene"

src/core/RasterEffects/brightnesscontrasteffect.frag, src/core/RasterEffects/colorizeeffect.frag, src/core/RasterEffects/motionblureffect.cpp, src/core/RasterEffects/noisefadeeffect.frag, src/core/RasterEffects/openglrastereffectcaller.cpp, src/core/RasterEffects/wipeeffect.frag, src/core/ShaderEffects/shadereffectprogram.cpp, src/core/appsupport.cpp, src/core/appsupport.h, src/core/glhelpers.cpp, src/core/shaders/maxalpha.frag
Fix deprecated `texture2D` and remove workarounds.
External shaders has also been updated: https://github.com/friction2d/friction-shader-plugins/pull/2 (will be merged after this PR).
Ref: #272
=> Fix shader 'texture' usage

src/app/GUI/Expressions/expressiondialog.cpp
A simple UX change but it is much more common that you want to edit an expression than adding a easing to your timeline, do you agree?
=> Change Expressions "Editor" and "Easing" tabs order

src/app/GUI/Expressions/expressiondialog.cpp, src/core/Expressions/expression.cpp, src/core/Expressions/functions/clamp.conf, src/core/Expressions/functions/clamp.js, src/core/Private/esettings.h, src/core/appsupport.cpp, src/core/appsupport.h, src/core/coreresources.qrc
Support extending the default selection of JS functions in Qt, currently only supports functions bundled with Friction ('clamp'), but can easily be modified to scan a user defined directory.
Added 'clamp' as an example:
@pgilfernandez
=> Support expressions plugins/bundle

src/app/GUI/mainwindow.cpp, src/app/GUI/timelinedockwidget.cpp, src/app/GUI/timelinedockwidget.h, src/core/Private/esettings.cpp, src/core/Private/esettings.h
I promise this is the last feature... it turned out pretty easy and I think it's also handy to have in 1.0:
https://github.com/user-attachments/assets/c39e1b6b-349b-4a56-9113-170244705410
The only thing to discuss (apart from if you want it inside v1.0 indeed, it's your decision) is how the GUI would change to accommodate this new option:
- as it is now, as a different play button: I would design a just outlined Play button to make it different than the normal "rendering" one
- or make it a checkbox next to the loop button (Synfig does this way) where you can choose whether you want to play rendering frames or this new "preview button".
Maybe it is interesting to say that the preview plays at realtime if you computer is capable to do it, if not there is no "dropping frames" feature …
=> Playback based on preview steps

src/app/GUI/mainwindow.cpp, src/core/actions.cpp, src/core/actions.h
Paste SVG from clipboard (Shift+ctrl/cmd+v).
https://github.com/user-attachments/assets/0049dc22-ef5f-4153-9e70-73a282b25170
Only tested on Linux and macOS.
**NOTE:** Inkscape and the clipboard is broken on macOS, you will not be able to paste from Inkscape (it produces an raster image and HTML junk), not our problem (https://gitlab.com/inkscape/inbox/-/issues/10924).
=> Support paste SVG from clipboard

src/app/GUI/mainwindow.cpp, src/app/GUI/mainwindow.h, src/core/Animators/outlinesettingsanimator.h, src/core/Animators/paintsettingsanimator.cpp, src/core/Animators/paintsettingsanimator.h, src/core/Boxes/pathbox.cpp, src/core/Boxes/textbox.cpp, src/core/Private/esettings.h, src/core/appsupport.cpp, src/core/appsupport.h, src/core/canvas.cpp, src/core/canvasmouseevents.cpp, src/ui/dialogs/scenesettingsdialog.cpp, src/ui/widgets/fillstrokesettings.cpp
Based on feedback in https://github.com/orgs/friction2d/discussions/488 I did some changes to the stroke workflow.
* Stroke color and width are now stored for reuse on new draw/stroke action (rectangle/circle)
* Right-click in draw mode will unselect last draw action (or any selected)
* This allows for changes to color/width during draw session
@pgilfernandez @AptGetMe
https://github.com/user-attachments/assets/a741f7f1-6480-4236-a153-bdf40f771aa9
=> UX: Draw/Stroke/Fill better workflow

src/core/Boxes/boundingbox.cpp, src/core/Boxes/containerbox.cpp
I've added support for exporting to SVG with `DstOut` layers (inverted masks).
The same way it was important to set your mask layer to **white color** for all the objects into your `DstIn`, now in the "inverted mask" the color has to be **black**.
I guess you know it (we might have talked about this before) but the behavior or final result of the blending modes are not the same inside Friction and exported SVG. BTW, SVG masks are cooler as they don't just take into account the shapes but the color (white, shades of grey and black) so it's possible to create more complex effects like the one in the previously example. [Here is the Friction project](https://github.com/user-attachments/files/19126892/mask.zip) just in case you want to play with it.
Cheers
=> SVG Export: added DstOut blend mode

src/app/GUI/timelinedockwidget.cpp, src/app/GUI/timelinedockwidget.h
I find this one pretty handy, at least for simple web animations. It's also transparent for users that don't want to use it as it is "hidden" in rewind and fastforward buttons.
Rewind and fastforward gets step by scene range quarters if pressing `shift` modifier.
https://github.com/user-attachments/assets/ec351214-2212-432d-8725-c9ee8a4667f9
Cheers
=> Rewind / Fast Forward by quarters

src/app/GUI/animationdockwidget.cpp, src/app/GUI/animationdockwidget.h, src/app/GUI/graphboxeslist.cpp, src/app/GUI/keysview.h, src/core/Animators/animator.cpp, src/core/Animators/animator.h
Using the new icons PRd to https://github.com/friction2d/friction-icon-theme/pull/29
This feature adds a zoom icon for zooming vertical:
- if less than 2 keyframes selected: it zooms to scene range
- if 2 or more keyframes selected: it zooms to the keyframes selection
https://github.com/user-attachments/assets/623a3668-ddb9-4460-a5aa-22178271dc83
I hope you like it 😊
=> Timeline horizontal zoom (and button)

src/core/Boxes/circle.cpp
This PR fixes https://github.com/friction2d/friction/issues/553
Depending on how circles are created within Friction, `horizontal radius` and `vertical radius` may take negative values.
When exporting those values to SVG and stored on `rx` and `ry` of an ellipse, negative values are not compliant and depending on your renderer it might turn into transparent shapes (the ellipse is there but not correctly drawn).
This PR ensures the exported values are always the absolute values.
[circles.friction.zip](https://github.com/user-attachments/files/21667841/circles.friction.zip)
**Friction v1.0 RC2**
**Friction v1.0 RC2 with this fix**    
I hope it doesn't break anything else...
Cheers
=> SVG export: ensure rx and ry values are always positive at export

src/ui/dialogs/scenesettingsdialog.cpp
Simple UX thing but handy if your scenes not always start at frame 0: place timebar at fMin (first scene frame) at scene creation so that you can start adding keyframes without the need to move it to the first real scene frame 😄
=> UX: place timebar on first scene frame at scene creation
