friction2d/friction

- src/app/GUI/ColorWidgets/colorpickingwidget.cpp
[Fix color picker widget for hidpi display.](https://github.com/friction2d/friction/commit/a9b8f3b686e02af40699d7a2d2f0540a15d44ac7)
> Fix color picker widget for hidpi display.

- src/app/GUI/Settings/pluginssettingswidget.cpp
- src/app/GUI/Settings/pluginssettingswidget.h
- src/app/effectsloader.cpp
- src/app/effectsloader.h
Added a basic shader manager in settings.
* List found plugins
* Enable/Disable individual plugin
Changes require restart.
> Basic shader manager

- src/app/GUI/Settings/performancesettingswidget.cpp
- src/app/GUI/Settings/performancesettingswidget.h
- src/core/RasterEffects/blureffect.cpp
- src/core/RasterEffects/brightnesscontrasteffect.cpp
- src/core/RasterEffects/colorizeeffect.cpp
- src/core/RasterEffects/motionblureffect.cpp
- src/core/RasterEffects/noisefadeeffect.cpp
- src/core/RasterEffects/shadoweffect.cpp
- src/core/RasterEffects/wipeeffect.cpp
- src/core/appsupport.cpp
- src/core/appsupport.h
- src/core/hardwareenums.h
You might need to force CPU/GPU on some effects.
* Motion Blur will perform better on a good CPU vs. GPU
* Some effects might have artifacts on GPU, CPU does not
> Preferences: added raster effects cpu/gpu option

- src/core/svgexporter.cpp
adding css style preview SVG to make it fit into screen
> add style for preview svg

- src/app/GUI/Settings/generalsettingswidget.cpp
- src/app/GUI/Settings/generalsettingswidget.h
- src/app/GUI/mainwindow.cpp
- src/app/GUI/mainwindow.h
- src/app/GUI/toolbox.cpp
- src/app/friction.qss
- src/core/Private/esettings.cpp
- src/core/Private/esettings.h
- src/ui/CMakeLists.txt
- src/ui/widgets/colortoolbar.cpp
- src/ui/widgets/toolbar.cpp
- src/ui/widgets/toolbar.h
- src/ui/widgets/vlabel.h
- src/ui/widgets/welcomedialog.cpp
New ToolBar gives much better UI flexibility:
https://github.com/user-attachments/assets/1aa15a11-04cf-4797-8134-05221e7fd407
> UI/UX: New ToolBar

- src/app/GUI/RenderWidgets/rendersettingsdialog.cpp
- src/app/GUI/RenderWidgets/rendersettingsdialog.h
- src/core/canvas.cpp
- src/core/canvas.h
> Renderer: support In/Out range

- src/ui/dialogs/scenesettingsdialog.cpp
- src/ui/dialogs/scenesettingsdialog.h
As suggested here https://github.com/friction2d/friction/issues/314
=)
> Duration value converts from frames to seconds and viceversa

- src/core/canvas.cpp
- src/core/canvas.h
- src/ui/widgets/framescrollbar.cpp
- src/ui/widgets/framescrollbar.h
Initial support for interactive markers/in/out, may contain bugs.
https://github.com/user-attachments/assets/7bbce154-c28e-4827-9099-9b73352de5b8
> Timeline: interactive markers/in/out

- src/core/Animators/staticcomplexanimator.cpp
- src/core/PathEffects/subpatheffect.cpp
- src/core/PathEffects/subpatheffect.h
- src/core/ReadWrite/evformat.h
Updated version of PR #335 by @pgilfernandez
> Sub path effect offset (v2)

- src/core/canvasmouseinteractions.cpp
Provide a way to pick (pixel) color in a sandbox (flatpak) and wayland, also avoid elevated permissions on macOS.
Keep old code as a fallback.
**Not tested on either configurations (only Linux/X11) :smile:**
> Update Color Picker

- src/app/GUI/extraactions.cpp
- src/app/friction.qss
- src/core/Boxes/boundingbox.cpp
- src/core/Boxes/boundingbox.h
- src/core/canvas.h
- src/core/canvasselectedboxesactions.cpp
- src/ui/widgets/alignwidget.cpp
- src/ui/widgets/alignwidget.h
> Support pivot alignment (v2)

- src/core/FileCacheHandlers/videostreamsdata.cpp
Should fix issue with wrong FPS on some videos.
Limited testing.
Fixes #397
> VideoStream: fix detected FPS

- src/core/canvas.cpp
- src/core/canvas.h
Support undo/redo on scene dimension/range change.
*Probably more properties that also need undo, let me know.*
> Undo: support scene changes

- src/ui/widgets/qrealanimatorvalueslider.cpp
- src/ui/widgets/qrealanimatorvalueslider.h
- Move mouse/gesture swipe + shift = uniform
- Edit mode: shift + enter = uniform
- ~Todo: macOS swipe + shift~
- ~Todo: remove debug stuff~
Fixes: #444 *(and possible others, will need to check)*
~Only tested on Linux, will need to add code for macOS gestures.~
This is the last feature PR before RC1.
> Value slider: fixes + uniform support

- src/app/GUI/timelinedockwidget.cpp
With this simple change the field gets updated with mouse wheel
> Update mCurrentFrameSpin with mouse wheel

- src/app/GUI/mainwindow.cpp
- src/app/GUI/mainwindow.h
- src/core/Expressions/expressionpresets.cpp
- src/core/Expressions/expressionpresets.h
- src/core/Expressions/presets/copyX.fexpr
- src/core/Expressions/presets/copyY.fexpr
- src/core/Expressions/presets/lerp.fexpr
- src/core/Expressions/presets/noise.fexpr
- src/core/Expressions/presets/orbitX.fexpr
- src/core/Expressions/presets/orbitY.fexpr
- src/core/Expressions/presets/oscillation.fexpr
- src/core/Expressions/presets/rotation.fexpr
- src/core/Expressions/presets/time.fexpr
- src/core/Expressions/presets/trackObject.fexpr
- src/core/Expressions/presets/wave.fexpr
- src/core/Expressions/presets/wiggle.fexpr
- src/core/coreresources.qrc
> Expression presets v2

- src/core/Expressions/presets/orbitX.fexpr
- src/core/Expressions/presets/orbitY.fexpr
- src/core/appsupport.cpp
- src/ui/widgets/performancesettingswidget.cpp
> Fix various typos

- src/app/GUI/mainwindow.cpp
> Added links to Friction website and Documentation on Help menu

- src/scripts/build_mac_ci.sh
- src/ui/dialogs/scenesettingsdialog.cpp
- src/ui/dialogs/scenesettingsdialog.h
Enable support for user defaults on new scene.
Replaces PR #475
> Scene Dialog: support user default

- src/core/videoencoder.cpp
Always convert PNG to unassociated alpha on render, as reported in issue #528
| Before    | After |
| -------- | ------- |
| <img width="1000" height="1300" alt="premul-untitled00001" src="https://github.com/user-attachments/assets/ec44628b-591f-4caf-954b-7726a004e45d" />  | <img width="1000" height="1300" alt="unpremul-untitled00001" src="https://github.com/user-attachments/assets/2e06cfeb-e8db-4552-be12-6b9908161193" />    |
> PNG: convert to unpremultiplied

- src/core/canvasmouseinteractions.cpp
> Invert shear X mouse direction
